const GET_ALL_POST = "GET_ALL_POST";
const GET_ALL_SPECIALITIES = "GET_ALL_SPECIALITIES";
const GET_ALL_COURSES = "GET_ALL_COURSES";
const GET_ALL_TEACHERS = "GET_ALL_TEACHERS";

const GET_POST = "GET_POST";
const GET_SPECIALITY = "GET_SPECIALITY";
const GET_COURSE = "GET_COURSE";
const GET_FRAGMENT = "GET_FRAGMENT";

export {
  GET_ALL_POST,
  GET_ALL_SPECIALITIES,
  GET_ALL_COURSES,
  GET_ALL_TEACHERS,
  GET_POST,
  GET_SPECIALITY,
  GET_COURSE,
  GET_FRAGMENT
};
